# Generated by Django 5.2.8 on 2026-09-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gpslog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gpspoint",
            name="encrypted_payload",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
