# Generated by Django 5.2.8 on 2026-09-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gpslog", "0003_gpspoint_encrypted_payload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gpspoint",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gpspoint",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
