# Generated by Django 5.2.8 on 2026-04-01 14:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CO2Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("icon", models.CharField(default="fas fa-smog", max_length=64)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CO2 Category",
                "verbose_name_plural": "CO2 Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CO2Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("description", models.CharField(max_length=256)),
                (
                    "amount_kg",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="CO2 equivalent in kg",
                        max_digits=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="environment.co2category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CO2 Entry",
                "verbose_name_plural": "CO2 Entries",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="CO2Offset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("description", models.CharField(max_length=256)),
                (
                    "amount_kg",
                    models.DecimalField(
                        decimal_places=3, help_text="CO2 offset in kg", max_digits=10
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=128, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "CO2 Offset",
                "verbose_name_plural": "CO2 Offsets",
                "ordering": ["-date"],
            },
        ),
    ]
