# Generated by Django 5.2.8 on 2026-04-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("environment", "0002_icon_phosphor_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="co2category",
            name="icon",
            field=models.CharField(default="ph ph-cloud-fog", max_length=64),
        ),
    ]
