# Generated by Django 5.0.6 on 2024-11-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mood", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
