# Generated by Django 5.0.6 on 2024-12-25 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mood", "0002_activity_hidden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mood",
            name="value",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(255),
                ]
            ),
        ),
    ]
