# Generated by Django 5.2.8 on 2026-04-01 14:24

import django.db.models.deletion
import moodyduck.common.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmotionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emotion", models.CharField(max_length=128)),
                ("percentage", moodyduck.common.fields.PercentageField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ThoughtRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=128, null=True)),
                ("situation", models.TextField(blank=True, null=True)),
                ("thoughts", models.TextField(blank=True, null=True)),
                ("pro_facts", models.TextField(blank=True, null=True)),
                ("con_facts", models.TextField(blank=True, null=True)),
                ("realistic", models.TextField(blank=True, null=True)),
                ("outcome", models.TextField(blank=True, null=True)),
                ("complete", models.BooleanField(default=False)),
                ("emotions", models.ManyToManyField(to="cbt.emotionrecord")),
                (
                    "emotions_now",
                    models.ManyToManyField(
                        related_name="emotions_now", to="cbt.emotionrecord"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
