# Generated by Django 5.2.8 on 2026-04-02 16:29

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("icon", models.CharField(default="fas fa-heart", max_length=64)),
                ("unit", models.CharField(blank=True, max_length=12, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HealthRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=12, null=True
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="health.healthlog",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="health.healthparameter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("icon", models.CharField(default="fas fa-tablets", max_length=64)),
                (
                    "supply",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("default_refill", models.PositiveSmallIntegerField(default=1)),
                (
                    "prn",
                    models.BooleanField(
                        default=False, help_text="As needed (pro re nata)"
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MedicationSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cycle_type",
                    models.IntegerField(
                        choices=[(0, "Days"), (1, "Weeks"), (2, "Months")]
                    ),
                ),
                ("cycle_count", models.IntegerField(default=1)),
                ("first", models.DateField(default=datetime.date.today)),
                ("last", models.DateField(blank=True, null=True)),
                (
                    "morning",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "noon",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "evening",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "night",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="health.medication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicationCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "time",
                    models.IntegerField(
                        choices=[
                            (0, "Morning"),
                            (1, "Noon"),
                            (2, "Evening"),
                            (3, "Night"),
                        ]
                    ),
                ),
                ("count", models.DecimalField(decimal_places=2, max_digits=5)),
                ("taken", models.BooleanField(default=False)),
                (
                    "medication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="health.medication",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="health.medicationschedule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("morning_from", models.TimeField(default=datetime.time(6, 0))),
                ("morning_till", models.TimeField(default=datetime.time(10, 0))),
                ("noon_from", models.TimeField(default=datetime.time(12, 0))),
                ("noon_till", models.TimeField(default=datetime.time(14, 0))),
                ("evening_from", models.TimeField(default=datetime.time(19, 0))),
                ("evening_till", models.TimeField(default=datetime.time(21, 0))),
                ("night_from", models.TimeField(default=datetime.time(22, 0))),
                ("night_till", models.TimeField(default=datetime.time(23, 0))),
                ("notifications", models.BooleanField(default=True)),
                ("refill_reminder", models.PositiveSmallIntegerField(default=7)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
