# Generated by Django 5.2.8 on 2026-04-18 08:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0002_icon_phosphor_migration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthparameter",
            name="icon",
            field=models.CharField(default="ph ph-heart", max_length=64),
        ),
        migrations.AlterField(
            model_name="medication",
            name="icon",
            field=models.CharField(default="ph ph-pill", max_length=64),
        ),
        migrations.CreateModel(
            name="Vaccination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "target_disease",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("administered_on", models.DateField(default=datetime.date.today)),
                ("provider", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "batch_number",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("next_due", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-administered_on", "name"],
            },
        ),
    ]
