# Generated by Django 5.2.8 on 2026-09-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0005_basicmedicalinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicmedicalinfo",
            name="encrypted_payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthlog",
            name="encrypted_payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="encrypted_payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="medication",
            name="encrypted_payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vaccination",
            name="encrypted_payload",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
