# Generated by Django 5.2.8 on 2026-09-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0006_basicmedicalinfo_encrypted_payload_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medication",
            name="name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="vaccination",
            name="name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
