# Generated by Django 6.1.1 on 2026-09-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_alter_medication_name_alter_vaccination_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccination',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='administered_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
