# Generated by Django 6.1.1 on 2026-09-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("health", "0008_alter_vaccination_administered_on_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="healthparameter",
            name="encrypted_payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="healthparameter",
            name="name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
