# Generated by Django 6.1.1 on 2026-09-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_healthparameter_encrypted_payload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthparameter',
            name='icon',
            field=models.CharField(blank=True, default='ph ph-heart', max_length=64, null=True),
        ),
    ]
