# Generated by Django 5.2.8 on 2026-04-01 14:24

import colorfield.fields
import datetime
import django.db.models.deletion
import moodyduck.common.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HabitSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("icon", models.CharField(default="fas fa-user-clock", max_length=64)),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#000000", image_field=None, max_length=25, samples=None
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DailyHabitSchedule",
            fields=[
                (
                    "habitschedule_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="habits.habitschedule",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("habits.habitschedule",),
        ),
        migrations.CreateModel(
            name="DateHabitSchedule",
            fields=[
                (
                    "habitschedule_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="habits.habitschedule",
                    ),
                ),
                ("date", models.DateField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("habits.habitschedule",),
        ),
        migrations.CreateModel(
            name="MonthlyHabitSchedule",
            fields=[
                (
                    "habitschedule_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="habits.habitschedule",
                    ),
                ),
                ("day", moodyduck.common.fields.DayOfMonthField()),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("habits.habitschedule",),
        ),
        migrations.CreateModel(
            name="WeeklyHabitSchedule",
            fields=[
                (
                    "habitschedule_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="habits.habitschedule",
                    ),
                ),
                ("weekdays", moodyduck.common.fields.WeekdayField(max_length=200)),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
            bases=("habits.habitschedule",),
        ),
        migrations.AddField(
            model_name="habitschedule",
            name="habit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="habits.habit"
            ),
        ),
        migrations.CreateModel(
            name="HabitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="habits.habit"
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
