# Generated by Django 5.2.8 on 2026-04-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_icon_phosphor_migration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailyhabitschedule",
            options={},
        ),
        migrations.AlterModelOptions(
            name="datehabitschedule",
            options={},
        ),
        migrations.AlterModelOptions(
            name="habitschedule",
            options={},
        ),
        migrations.AlterModelOptions(
            name="monthlyhabitschedule",
            options={},
        ),
        migrations.AlterModelOptions(
            name="weeklyhabitschedule",
            options={},
        ),
        migrations.AlterField(
            model_name="habit",
            name="icon",
            field=models.CharField(default="ph ph-user-gear", max_length=64),
        ),
    ]
