# Generated by Django 6.1.1 on 2026-09-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0004_repair_legacy_schema"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={"ordering": ["-pk"]},
        ),
        migrations.AddField(
            model_name="habit",
            name="encrypted_payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="habitlog",
            name="encrypted_payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="habit",
            name="name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
