# Generated by Django 6.1.1 on 2026-10-04 20:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("habits", "0005_add_encrypted_payload"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="color",
        ),
    ]
