# Generated by Django 6.1.1 on 2026-10-04 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_remove_habit_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='name',
        ),
    ]
