# Generated by Django 5.2.8 on 2026-09-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mood", "0005_alter_activity_icon_alter_activitycategory_icon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="encrypted_payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mood",
            name="encrypted_payload",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="status",
            name="encrypted_payload",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
