# Generated by Django 5.2.8 on 2026-09-06 15:11

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mood", "0006_activity_encrypted_payload_mood_encrypted_payload_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#000000",
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="icon",
            field=models.CharField(
                blank=True, default="ph ph-check", max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="mood",
            name="color",
            field=colorfield.fields.ColorField(
                blank=True,
                default="#000000",
                image_field=None,
                max_length=25,
                null=True,
                samples=None,
            ),
        ),
        migrations.AlterField(
            model_name="mood",
            name="icon",
            field=models.CharField(
                blank=True, default="ph ph-star", max_length=64, null=True
            ),
        ),
        migrations.AlterField(
            model_name="mood",
            name="name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="mood",
            name="value",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(255),
                ],
            ),
        ),
    ]
