# Generated by Django 5.2.8 on 2026-09-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mood", "0007_alter_activity_color_alter_activity_icon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="statusmedia",
            name="encrypted_payload",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
