# Generated by Django 6.1.1 on 2026-10-04 20:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mood", "0011_activitycategory_encrypted_payload_and_more"),
    ]

    operations = []
