# Generated by Django 6.1.1 on 2026-10-06 19:02

import colorfield.fields
from django.db import migrations


def make_color_columns_nullable(apps, schema_editor):
    # Migration 0013 updated Django's state but never issued ALTER COLUMN on
    # databases where the color column already existed as NOT NULL. This pass
    # finds those columns and makes them nullable using the database-agnostic
    # schema editor API.
    connection = schema_editor.connection
    targets = [("mood", "Mood"), ("mood", "Activity"), ("mood", "ActivityCategory")]
    for app_label, model_name in targets:
        model = apps.get_model(app_label, model_name)
        table = model._meta.db_table
        with connection.cursor() as cursor:
            cols = {
                c.name: c
                for c in connection.introspection.get_table_description(cursor, table)
            }
        col = cols.get("color")
        if col is None or col.null_ok:
            continue
        old_field = colorfield.fields.ColorField(
            max_length=25,
            null=False,
            blank=False,
            default="",
            image_field=None,
            samples=None,
        )
        old_field.set_attributes_from_name("color")
        new_field = colorfield.fields.ColorField(
            max_length=25,
            null=True,
            blank=True,
            default=None,
            image_field=None,
            samples=None,
        )
        new_field.set_attributes_from_name("color")
        schema_editor.alter_field(model, old_field, new_field)


class Migration(migrations.Migration):
    dependencies = [
        ("mood", "0013_activity_color_activitycategory_color_mood_color"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[],
            database_operations=[
                migrations.RunPython(
                    make_color_columns_nullable, migrations.RunPython.noop
                ),
            ],
        ),
    ]
