# Generated by Django 5.2.8 on 2026-04-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dreams", "0002_icon_phosphor_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="theme",
            name="icon",
            field=models.CharField(default="ph ph-bed", max_length=64),
        ),
        migrations.AlterField(
            model_name="themerating",
            name="icon",
            field=models.CharField(default="ph ph-star", max_length=64),
        ),
    ]
