# Generated by Django 5.2.8 on 2026-09-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dreams", "0003_alter_theme_icon_alter_themerating_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="dream",
            name="encrypted_payload",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
