# Generated by Django 5.2.8 on 2026-09-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dreams", "0004_dream_encrypted_payload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dream",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dream",
            name="title",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
