# Generated by Django 5.2.8 on 2026-09-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dreams", "0005_alter_dream_content_alter_dream_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="dreammedia",
            name="encrypted_payload",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
